// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eum.proto

package com.finger.pb;

public final class PBEnum {
  private PBEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code xapp.eum.MOVING_TYPE}
   */
  public enum MOVING_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOVING_TO_LEFT = 1;</code>
     */
    MOVING_TO_LEFT(0, 1),
    /**
     * <code>MOVING_TO_RIGHT = 2;</code>
     */
    MOVING_TO_RIGHT(1, 2),
    /**
     * <code>MOVING_NONE = 3;</code>
     */
    MOVING_NONE(2, 3),
    ;

    /**
     * <code>MOVING_TO_LEFT = 1;</code>
     */
    public static final int MOVING_TO_LEFT_VALUE = 1;
    /**
     * <code>MOVING_TO_RIGHT = 2;</code>
     */
    public static final int MOVING_TO_RIGHT_VALUE = 2;
    /**
     * <code>MOVING_NONE = 3;</code>
     */
    public static final int MOVING_NONE_VALUE = 3;


    public final int getNumber() { return value; }

    public static MOVING_TYPE valueOf(int value) {
      switch (value) {
        case 1: return MOVING_TO_LEFT;
        case 2: return MOVING_TO_RIGHT;
        case 3: return MOVING_NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MOVING_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MOVING_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MOVING_TYPE>() {
            public MOVING_TYPE findValueByNumber(int number) {
              return MOVING_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final MOVING_TYPE[] VALUES = values();

    public static MOVING_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MOVING_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.MOVING_TYPE)
  }

  /**
   * Protobuf enum {@code xapp.eum.ENUM_Sound}
   */
  public enum ENUM_Sound
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>E_Sbeida = 1;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sbeida(0, 1),
    /**
     * <code>E_Sbeidasi = 2;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sbeidasi(1, 2),
    /**
     * <code>E_Scaiji = 3;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Scaiji(2, 3),
    /**
     * <code>E_Sdianneng = 4;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sdianneng(3, 4),
    /**
     * <code>E_Sgongji = 5;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sgongji(4, 5),
    /**
     * <code>E_Spk = 6;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Spk(5, 6),
    /**
     * <code>E_Suianjian = 7;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Suianjian(6, 7),
    /**
     * <code>E_Swajue1 = 8;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Swajue1(7, 8),
    /**
     * <code>E_Swanchengrenwu = 9;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Swanchengrenwu(8, 9),
    /**
     * <code>E_Syaosai4 = 10;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Syaosai4(9, 10),
    /**
     * <code>E_Syaosaiui2 = 11;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Syaosaiui2(10, 11),
    /**
     * <code>E_Szhuuianjian = 12;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Szhuuianjian(11, 12),
    /**
     * <code>E_Szoulu1 = 13;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Szoulu1(12, 13),
    /**
     * <code>E_Szuoyou = 14;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Szuoyou(13, 14),
    /**
     * <code>E_Sguaiwusi = 15;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sguaiwusi(14, 15),
    /**
     * <code>E_Sdubo = 16;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sdubo(15, 16),
    /**
     * <code>E_Stianfu = 17;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Stianfu(16, 17),
    /**
     * <code>E_Sziyuanbugou = 18;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sziyuanbugou(17, 18),
    /**
     * <code>E_Sshengtaiyuanjiahao = 19;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Sshengtaiyuanjiahao(18, 19),
    /**
     * <code>E_Schengjiushengjitubiao = 20;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Schengjiushengjitubiao(19, 20),
    /**
     * <code>E_Szimu = 21;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    E_Szimu(20, 21),
    ;

    /**
     * <code>E_Sbeida = 1;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sbeida_VALUE = 1;
    /**
     * <code>E_Sbeidasi = 2;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sbeidasi_VALUE = 2;
    /**
     * <code>E_Scaiji = 3;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Scaiji_VALUE = 3;
    /**
     * <code>E_Sdianneng = 4;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sdianneng_VALUE = 4;
    /**
     * <code>E_Sgongji = 5;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sgongji_VALUE = 5;
    /**
     * <code>E_Spk = 6;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Spk_VALUE = 6;
    /**
     * <code>E_Suianjian = 7;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Suianjian_VALUE = 7;
    /**
     * <code>E_Swajue1 = 8;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Swajue1_VALUE = 8;
    /**
     * <code>E_Swanchengrenwu = 9;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Swanchengrenwu_VALUE = 9;
    /**
     * <code>E_Syaosai4 = 10;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Syaosai4_VALUE = 10;
    /**
     * <code>E_Syaosaiui2 = 11;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Syaosaiui2_VALUE = 11;
    /**
     * <code>E_Szhuuianjian = 12;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Szhuuianjian_VALUE = 12;
    /**
     * <code>E_Szoulu1 = 13;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Szoulu1_VALUE = 13;
    /**
     * <code>E_Szuoyou = 14;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Szuoyou_VALUE = 14;
    /**
     * <code>E_Sguaiwusi = 15;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sguaiwusi_VALUE = 15;
    /**
     * <code>E_Sdubo = 16;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sdubo_VALUE = 16;
    /**
     * <code>E_Stianfu = 17;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Stianfu_VALUE = 17;
    /**
     * <code>E_Sziyuanbugou = 18;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sziyuanbugou_VALUE = 18;
    /**
     * <code>E_Sshengtaiyuanjiahao = 19;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Sshengtaiyuanjiahao_VALUE = 19;
    /**
     * <code>E_Schengjiushengjitubiao = 20;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Schengjiushengjitubiao_VALUE = 20;
    /**
     * <code>E_Szimu = 21;</code>
     *
     * <pre>
     *1 s
     * </pre>
     */
    public static final int E_Szimu_VALUE = 21;


    public final int getNumber() { return value; }

    public static ENUM_Sound valueOf(int value) {
      switch (value) {
        case 1: return E_Sbeida;
        case 2: return E_Sbeidasi;
        case 3: return E_Scaiji;
        case 4: return E_Sdianneng;
        case 5: return E_Sgongji;
        case 6: return E_Spk;
        case 7: return E_Suianjian;
        case 8: return E_Swajue1;
        case 9: return E_Swanchengrenwu;
        case 10: return E_Syaosai4;
        case 11: return E_Syaosaiui2;
        case 12: return E_Szhuuianjian;
        case 13: return E_Szoulu1;
        case 14: return E_Szuoyou;
        case 15: return E_Sguaiwusi;
        case 16: return E_Sdubo;
        case 17: return E_Stianfu;
        case 18: return E_Sziyuanbugou;
        case 19: return E_Sshengtaiyuanjiahao;
        case 20: return E_Schengjiushengjitubiao;
        case 21: return E_Szimu;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ENUM_Sound>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ENUM_Sound>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ENUM_Sound>() {
            public ENUM_Sound findValueByNumber(int number) {
              return ENUM_Sound.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(1);
    }

    private static final ENUM_Sound[] VALUES = values();

    public static ENUM_Sound valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ENUM_Sound(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.ENUM_Sound)
  }

  /**
   * Protobuf enum {@code xapp.eum.ENUM_UI_PAGE}
   */
  public enum ENUM_UI_PAGE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>E_UImain = 1;</code>
     *
     * <pre>
     *空间要塞
     * </pre>
     */
    E_UImain(0, 1),
    /**
     * <code>E_UIvillage = 2;</code>
     *
     * <pre>
     *实验室
     * </pre>
     */
    E_UIvillage(1, 2),
    /**
     * <code>E_UIpub = 3;</code>
     *
     * <pre>
     *星港营地
     * </pre>
     */
    E_UIpub(2, 3),
    /**
     * <code>E_UIbag = 4;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIbag(3, 4),
    /**
     * <code>E_UIbattle = 5;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIbattle(4, 5),
    /**
     * <code>E_UIend = 6;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIend(5, 6),
    /**
     * <code>E_UImap = 7;</code>
     *
     * <pre>
     * </pre>
     */
    E_UImap(6, 7),
    /**
     * <code>E_UIbase = 8;</code>
     *
     * <pre>
     *基地
     * </pre>
     */
    E_UIbase(7, 8),
    /**
     * <code>E_UIexchange = 9;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    E_UIexchange(8, 9),
    /**
     * <code>E_UIequipment = 10;</code>
     *
     * <pre>
     *装备库
     * </pre>
     */
    E_UIequipment(9, 10),
    /**
     * <code>E_UIbarracks = 11;</code>
     *
     * <pre>
     *兵营
     * </pre>
     */
    E_UIbarracks(10, 11),
    /**
     * <code>E_UIset = 12;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIset(11, 12),
    /**
     * <code>E_UIlanuage = 13;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIlanuage(12, 13),
    /**
     * <code>E_UIloading = 14;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIloading(13, 14),
    /**
     * <code>E_UIshop = 15;</code>
     *
     * <pre>
     *钻石
     * </pre>
     */
    E_UIshop(14, 15),
    /**
     * <code>E_UIRecharge = 16;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIRecharge(15, 16),
    /**
     * <code>E_UIAchievement = 17;</code>
     *
     * <pre>
     *成就
     * </pre>
     */
    E_UIAchievement(16, 17),
    /**
     * <code>E_UITalent = 18;</code>
     *
     * <pre>
     *天赋
     * </pre>
     */
    E_UITalent(17, 18),
    /**
     * <code>E_UIBattleMessage = 19;</code>
     *
     * <pre>
     * </pre>
     */
    E_UIBattleMessage(18, 19),
    /**
     * <code>E_UItranslate = 20;</code>
     *
     * <pre>
     * </pre>
     */
    E_UItranslate(19, 20),
    /**
     * <code>E_UITask = 21;</code>
     */
    E_UITask(20, 21),
    /**
     * <code>__E_UIPerLoad = 1000;</code>
     */
    __E_UIPerLoad(21, 1000),
    ;

    /**
     * <code>E_UImain = 1;</code>
     *
     * <pre>
     *空间要塞
     * </pre>
     */
    public static final int E_UImain_VALUE = 1;
    /**
     * <code>E_UIvillage = 2;</code>
     *
     * <pre>
     *实验室
     * </pre>
     */
    public static final int E_UIvillage_VALUE = 2;
    /**
     * <code>E_UIpub = 3;</code>
     *
     * <pre>
     *星港营地
     * </pre>
     */
    public static final int E_UIpub_VALUE = 3;
    /**
     * <code>E_UIbag = 4;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIbag_VALUE = 4;
    /**
     * <code>E_UIbattle = 5;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIbattle_VALUE = 5;
    /**
     * <code>E_UIend = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIend_VALUE = 6;
    /**
     * <code>E_UImap = 7;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UImap_VALUE = 7;
    /**
     * <code>E_UIbase = 8;</code>
     *
     * <pre>
     *基地
     * </pre>
     */
    public static final int E_UIbase_VALUE = 8;
    /**
     * <code>E_UIexchange = 9;</code>
     *
     * <pre>
     *交易所
     * </pre>
     */
    public static final int E_UIexchange_VALUE = 9;
    /**
     * <code>E_UIequipment = 10;</code>
     *
     * <pre>
     *装备库
     * </pre>
     */
    public static final int E_UIequipment_VALUE = 10;
    /**
     * <code>E_UIbarracks = 11;</code>
     *
     * <pre>
     *兵营
     * </pre>
     */
    public static final int E_UIbarracks_VALUE = 11;
    /**
     * <code>E_UIset = 12;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIset_VALUE = 12;
    /**
     * <code>E_UIlanuage = 13;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIlanuage_VALUE = 13;
    /**
     * <code>E_UIloading = 14;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIloading_VALUE = 14;
    /**
     * <code>E_UIshop = 15;</code>
     *
     * <pre>
     *钻石
     * </pre>
     */
    public static final int E_UIshop_VALUE = 15;
    /**
     * <code>E_UIRecharge = 16;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIRecharge_VALUE = 16;
    /**
     * <code>E_UIAchievement = 17;</code>
     *
     * <pre>
     *成就
     * </pre>
     */
    public static final int E_UIAchievement_VALUE = 17;
    /**
     * <code>E_UITalent = 18;</code>
     *
     * <pre>
     *天赋
     * </pre>
     */
    public static final int E_UITalent_VALUE = 18;
    /**
     * <code>E_UIBattleMessage = 19;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UIBattleMessage_VALUE = 19;
    /**
     * <code>E_UItranslate = 20;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int E_UItranslate_VALUE = 20;
    /**
     * <code>E_UITask = 21;</code>
     */
    public static final int E_UITask_VALUE = 21;
    /**
     * <code>__E_UIPerLoad = 1000;</code>
     */
    public static final int __E_UIPerLoad_VALUE = 1000;


    public final int getNumber() { return value; }

    public static ENUM_UI_PAGE valueOf(int value) {
      switch (value) {
        case 1: return E_UImain;
        case 2: return E_UIvillage;
        case 3: return E_UIpub;
        case 4: return E_UIbag;
        case 5: return E_UIbattle;
        case 6: return E_UIend;
        case 7: return E_UImap;
        case 8: return E_UIbase;
        case 9: return E_UIexchange;
        case 10: return E_UIequipment;
        case 11: return E_UIbarracks;
        case 12: return E_UIset;
        case 13: return E_UIlanuage;
        case 14: return E_UIloading;
        case 15: return E_UIshop;
        case 16: return E_UIRecharge;
        case 17: return E_UIAchievement;
        case 18: return E_UITalent;
        case 19: return E_UIBattleMessage;
        case 20: return E_UItranslate;
        case 21: return E_UITask;
        case 1000: return __E_UIPerLoad;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ENUM_UI_PAGE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ENUM_UI_PAGE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ENUM_UI_PAGE>() {
            public ENUM_UI_PAGE findValueByNumber(int number) {
              return ENUM_UI_PAGE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(2);
    }

    private static final ENUM_UI_PAGE[] VALUES = values();

    public static ENUM_UI_PAGE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ENUM_UI_PAGE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.ENUM_UI_PAGE)
  }

  /**
   * Protobuf enum {@code xapp.eum.ENUM_UI_EVENT}
   */
  public enum ENUM_UI_EVENT
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>event_barry_low = 1;</code>
     */
    event_barry_low(0, 1),
    /**
     * <code>event_base = 2;</code>
     */
    event_base(1, 2),
    /**
     * <code>event_exchange = 3;</code>
     */
    event_exchange(2, 3),
    /**
     * <code>event_equipment = 4;</code>
     */
    event_equipment(3, 4),
    /**
     * <code>event_barracks = 5;</code>
     */
    event_barracks(4, 5),
    /**
     * <code>event_village = 6;</code>
     */
    event_village(5, 6),
    /**
     * <code>event_village2 = 7;</code>
     */
    event_village2(6, 7),
    /**
     * <code>event_achievement = 8;</code>
     */
    event_achievement(7, 8),
    /**
     * <code>event_pub = 9;</code>
     */
    event_pub(8, 9),
    /**
     * <code>event_talent = 10;</code>
     */
    event_talent(9, 10),
    /**
     * <code>event_luck = 11;</code>
     */
    event_luck(10, 11),
    /**
     * <code>event_shop = 12;</code>
     */
    event_shop(11, 12),
    /**
     * <code>event_base2 = 13;</code>
     */
    event_base2(12, 13),
    /**
     * <code>event_buji = 14;</code>
     */
    event_buji(13, 14),
    /**
     * <code>event_fenshi = 15;</code>
     */
    event_fenshi(14, 15),
    /**
     * <code>event_moku = 16;</code>
     */
    event_moku(15, 16),
    /**
     * <code>event_shengji = 17;</code>
     */
    event_shengji(16, 17),
    /**
     * <code>event_zhanchang = 18;</code>
     */
    event_zhanchang(17, 18),
    /**
     * <code>event_introduce = 25;</code>
     */
    event_introduce(18, 25),
    /**
     * <code>event_battle_alert = 26;</code>
     */
    event_battle_alert(19, 26),
    /**
     * <code>event_first_win = 31;</code>
     */
    event_first_win(20, 31),
    /**
     * <code>event_open_door = 33;</code>
     */
    event_open_door(21, 33),
    ;

    /**
     * <code>event_barry_low = 1;</code>
     */
    public static final int event_barry_low_VALUE = 1;
    /**
     * <code>event_base = 2;</code>
     */
    public static final int event_base_VALUE = 2;
    /**
     * <code>event_exchange = 3;</code>
     */
    public static final int event_exchange_VALUE = 3;
    /**
     * <code>event_equipment = 4;</code>
     */
    public static final int event_equipment_VALUE = 4;
    /**
     * <code>event_barracks = 5;</code>
     */
    public static final int event_barracks_VALUE = 5;
    /**
     * <code>event_village = 6;</code>
     */
    public static final int event_village_VALUE = 6;
    /**
     * <code>event_village2 = 7;</code>
     */
    public static final int event_village2_VALUE = 7;
    /**
     * <code>event_achievement = 8;</code>
     */
    public static final int event_achievement_VALUE = 8;
    /**
     * <code>event_pub = 9;</code>
     */
    public static final int event_pub_VALUE = 9;
    /**
     * <code>event_talent = 10;</code>
     */
    public static final int event_talent_VALUE = 10;
    /**
     * <code>event_luck = 11;</code>
     */
    public static final int event_luck_VALUE = 11;
    /**
     * <code>event_shop = 12;</code>
     */
    public static final int event_shop_VALUE = 12;
    /**
     * <code>event_base2 = 13;</code>
     */
    public static final int event_base2_VALUE = 13;
    /**
     * <code>event_buji = 14;</code>
     */
    public static final int event_buji_VALUE = 14;
    /**
     * <code>event_fenshi = 15;</code>
     */
    public static final int event_fenshi_VALUE = 15;
    /**
     * <code>event_moku = 16;</code>
     */
    public static final int event_moku_VALUE = 16;
    /**
     * <code>event_shengji = 17;</code>
     */
    public static final int event_shengji_VALUE = 17;
    /**
     * <code>event_zhanchang = 18;</code>
     */
    public static final int event_zhanchang_VALUE = 18;
    /**
     * <code>event_introduce = 25;</code>
     */
    public static final int event_introduce_VALUE = 25;
    /**
     * <code>event_battle_alert = 26;</code>
     */
    public static final int event_battle_alert_VALUE = 26;
    /**
     * <code>event_first_win = 31;</code>
     */
    public static final int event_first_win_VALUE = 31;
    /**
     * <code>event_open_door = 33;</code>
     */
    public static final int event_open_door_VALUE = 33;


    public final int getNumber() { return value; }

    public static ENUM_UI_EVENT valueOf(int value) {
      switch (value) {
        case 1: return event_barry_low;
        case 2: return event_base;
        case 3: return event_exchange;
        case 4: return event_equipment;
        case 5: return event_barracks;
        case 6: return event_village;
        case 7: return event_village2;
        case 8: return event_achievement;
        case 9: return event_pub;
        case 10: return event_talent;
        case 11: return event_luck;
        case 12: return event_shop;
        case 13: return event_base2;
        case 14: return event_buji;
        case 15: return event_fenshi;
        case 16: return event_moku;
        case 17: return event_shengji;
        case 18: return event_zhanchang;
        case 25: return event_introduce;
        case 26: return event_battle_alert;
        case 31: return event_first_win;
        case 33: return event_open_door;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ENUM_UI_EVENT>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ENUM_UI_EVENT>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ENUM_UI_EVENT>() {
            public ENUM_UI_EVENT findValueByNumber(int number) {
              return ENUM_UI_EVENT.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(3);
    }

    private static final ENUM_UI_EVENT[] VALUES = values();

    public static ENUM_UI_EVENT valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ENUM_UI_EVENT(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.ENUM_UI_EVENT)
  }

  /**
   * Protobuf enum {@code xapp.eum.ATTACK_TYPE}
   */
  public enum ATTACK_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AT_NORMAL = 1;</code>
     *
     * <pre>
     *普通攻击
     * </pre>
     */
    AT_NORMAL(0, 1),
    /**
     * <code>AT_BLOODY = 2;</code>
     *
     * <pre>
     *攻击眩晕
     * </pre>
     */
    AT_BLOODY(1, 2),
    /**
     * <code>AT_JUST_HEALTH = 3;</code>
     *
     * <pre>
     *纯加血
     * </pre>
     */
    AT_JUST_HEALTH(2, 3),
    /**
     * <code>AT_ATTACK_HEALTH = 4;</code>
     *
     * <pre>
     *吸血
     * </pre>
     */
    AT_ATTACK_HEALTH(3, 4),
    /**
     * <code>AT_ATTACK_POISON = 5;</code>
     *
     * <pre>
     *攻击和毒
     * </pre>
     */
    AT_ATTACK_POISON(4, 5),
    /**
     * <code>AT_ATTACK_LOW = 6;</code>
     *
     * <pre>
     *打人降敌人攻击
     * </pre>
     */
    AT_ATTACK_LOW(5, 6),
    /**
     * <code>AT_HEALTH_BLOODY = 7;</code>
     *
     * <pre>
     *加血眩晕
     * </pre>
     */
    AT_HEALTH_BLOODY(6, 7),
    /**
     * <code>AT_HEALTH_POISON = 8;</code>
     *
     * <pre>
     *回复和毒
     * </pre>
     */
    AT_HEALTH_POISON(7, 8),
    /**
     * <code>AT_HEALTH_LOW = 9;</code>
     *
     * <pre>
     *回复减伤
     * </pre>
     */
    AT_HEALTH_LOW(8, 9),
    ;

    /**
     * <code>AT_NORMAL = 1;</code>
     *
     * <pre>
     *普通攻击
     * </pre>
     */
    public static final int AT_NORMAL_VALUE = 1;
    /**
     * <code>AT_BLOODY = 2;</code>
     *
     * <pre>
     *攻击眩晕
     * </pre>
     */
    public static final int AT_BLOODY_VALUE = 2;
    /**
     * <code>AT_JUST_HEALTH = 3;</code>
     *
     * <pre>
     *纯加血
     * </pre>
     */
    public static final int AT_JUST_HEALTH_VALUE = 3;
    /**
     * <code>AT_ATTACK_HEALTH = 4;</code>
     *
     * <pre>
     *吸血
     * </pre>
     */
    public static final int AT_ATTACK_HEALTH_VALUE = 4;
    /**
     * <code>AT_ATTACK_POISON = 5;</code>
     *
     * <pre>
     *攻击和毒
     * </pre>
     */
    public static final int AT_ATTACK_POISON_VALUE = 5;
    /**
     * <code>AT_ATTACK_LOW = 6;</code>
     *
     * <pre>
     *打人降敌人攻击
     * </pre>
     */
    public static final int AT_ATTACK_LOW_VALUE = 6;
    /**
     * <code>AT_HEALTH_BLOODY = 7;</code>
     *
     * <pre>
     *加血眩晕
     * </pre>
     */
    public static final int AT_HEALTH_BLOODY_VALUE = 7;
    /**
     * <code>AT_HEALTH_POISON = 8;</code>
     *
     * <pre>
     *回复和毒
     * </pre>
     */
    public static final int AT_HEALTH_POISON_VALUE = 8;
    /**
     * <code>AT_HEALTH_LOW = 9;</code>
     *
     * <pre>
     *回复减伤
     * </pre>
     */
    public static final int AT_HEALTH_LOW_VALUE = 9;


    public final int getNumber() { return value; }

    public static ATTACK_TYPE valueOf(int value) {
      switch (value) {
        case 1: return AT_NORMAL;
        case 2: return AT_BLOODY;
        case 3: return AT_JUST_HEALTH;
        case 4: return AT_ATTACK_HEALTH;
        case 5: return AT_ATTACK_POISON;
        case 6: return AT_ATTACK_LOW;
        case 7: return AT_HEALTH_BLOODY;
        case 8: return AT_HEALTH_POISON;
        case 9: return AT_HEALTH_LOW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ATTACK_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ATTACK_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ATTACK_TYPE>() {
            public ATTACK_TYPE findValueByNumber(int number) {
              return ATTACK_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(4);
    }

    private static final ATTACK_TYPE[] VALUES = values();

    public static ATTACK_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ATTACK_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.ATTACK_TYPE)
  }

  /**
   * Protobuf enum {@code xapp.eum.MONSTER_ATTACK_TYPE}
   */
  public enum MONSTER_ATTACK_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MA_NORMAL = 1;</code>
     *
     * <pre>
     *普通攻击
     * </pre>
     */
    MA_NORMAL(0, 1),
    /**
     * <code>MA_BURNING = 2;</code>
     *
     * <pre>
     *全体焚烧
     * </pre>
     */
    MA_BURNING(1, 2),
    /**
     * <code>MA_SHIELD = 3;</code>
     *
     * <pre>
     *护盾
     * </pre>
     */
    MA_SHIELD(2, 3),
    /**
     * <code>MA_ALIVE = 4;</code>
     *
     * <pre>
     *复活
     * </pre>
     */
    MA_ALIVE(3, 4),
    /**
     * <code>MA_ICE = 5;</code>
     *
     * <pre>
     *冰封
     * </pre>
     */
    MA_ICE(4, 5),
    /**
     * <code>MA_HEALTH = 6;</code>
     *
     * <pre>
     *治疗
     * </pre>
     */
    MA_HEALTH(5, 6),
    ;

    /**
     * <code>MA_NORMAL = 1;</code>
     *
     * <pre>
     *普通攻击
     * </pre>
     */
    public static final int MA_NORMAL_VALUE = 1;
    /**
     * <code>MA_BURNING = 2;</code>
     *
     * <pre>
     *全体焚烧
     * </pre>
     */
    public static final int MA_BURNING_VALUE = 2;
    /**
     * <code>MA_SHIELD = 3;</code>
     *
     * <pre>
     *护盾
     * </pre>
     */
    public static final int MA_SHIELD_VALUE = 3;
    /**
     * <code>MA_ALIVE = 4;</code>
     *
     * <pre>
     *复活
     * </pre>
     */
    public static final int MA_ALIVE_VALUE = 4;
    /**
     * <code>MA_ICE = 5;</code>
     *
     * <pre>
     *冰封
     * </pre>
     */
    public static final int MA_ICE_VALUE = 5;
    /**
     * <code>MA_HEALTH = 6;</code>
     *
     * <pre>
     *治疗
     * </pre>
     */
    public static final int MA_HEALTH_VALUE = 6;


    public final int getNumber() { return value; }

    public static MONSTER_ATTACK_TYPE valueOf(int value) {
      switch (value) {
        case 1: return MA_NORMAL;
        case 2: return MA_BURNING;
        case 3: return MA_SHIELD;
        case 4: return MA_ALIVE;
        case 5: return MA_ICE;
        case 6: return MA_HEALTH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MONSTER_ATTACK_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MONSTER_ATTACK_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MONSTER_ATTACK_TYPE>() {
            public MONSTER_ATTACK_TYPE findValueByNumber(int number) {
              return MONSTER_ATTACK_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(5);
    }

    private static final MONSTER_ATTACK_TYPE[] VALUES = values();

    public static MONSTER_ATTACK_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MONSTER_ATTACK_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.MONSTER_ATTACK_TYPE)
  }

  /**
   * Protobuf enum {@code xapp.eum.TIlE_LAYER3}
   *
   * <pre>
   *LAYER3_MARK_BLACK=3;
   *LAYER3_MARK_DEEPED=2;
   *LAYER3_MARK_GREY=1;
   *LAYER3_MARK_NONE=0;
   * </pre>
   */
  public enum TIlE_LAYER3
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LAYER3_MARK_BEGIN = 81;</code>
     */
    LAYER3_MARK_BEGIN(0, 81),
    ;

    /**
     * <code>LAYER3_MARK_BEGIN = 81;</code>
     */
    public static final int LAYER3_MARK_BEGIN_VALUE = 81;


    public final int getNumber() { return value; }

    public static TIlE_LAYER3 valueOf(int value) {
      switch (value) {
        case 81: return LAYER3_MARK_BEGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER3>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER3>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER3>() {
            public TIlE_LAYER3 findValueByNumber(int number) {
              return TIlE_LAYER3.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(6);
    }

    private static final TIlE_LAYER3[] VALUES = values();

    public static TIlE_LAYER3 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TIlE_LAYER3(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TIlE_LAYER3)
  }

  /**
   * Protobuf enum {@code xapp.eum.TIlE_DEFINE}
   */
  public enum TIlE_DEFINE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LAYER2_TOWER_MIN = 30;</code>
     */
    LAYER2_TOWER_MIN(0, 30),
    /**
     * <code>LAYER2_TOWER_MAX = 56;</code>
     */
    LAYER2_TOWER_MAX(1, 56),
    ;

    /**
     * <code>LAYER2_TOWER_MIN = 30;</code>
     */
    public static final int LAYER2_TOWER_MIN_VALUE = 30;
    /**
     * <code>LAYER2_TOWER_MAX = 56;</code>
     */
    public static final int LAYER2_TOWER_MAX_VALUE = 56;


    public final int getNumber() { return value; }

    public static TIlE_DEFINE valueOf(int value) {
      switch (value) {
        case 30: return LAYER2_TOWER_MIN;
        case 56: return LAYER2_TOWER_MAX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TIlE_DEFINE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TIlE_DEFINE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TIlE_DEFINE>() {
            public TIlE_DEFINE findValueByNumber(int number) {
              return TIlE_DEFINE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(7);
    }

    private static final TIlE_DEFINE[] VALUES = values();

    public static TIlE_DEFINE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TIlE_DEFINE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TIlE_DEFINE)
  }

  /**
   * Protobuf enum {@code xapp.eum.TIlE_LAYER1}
   */
  public enum TIlE_LAYER1
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LAYER1_TILE_BG = 102;</code>
     *
     * <pre>
     *17*6
     * </pre>
     */
    LAYER1_TILE_BG(0, 102),
    ;

    /**
     * <code>LAYER1_TILE_BG = 102;</code>
     *
     * <pre>
     *17*6
     * </pre>
     */
    public static final int LAYER1_TILE_BG_VALUE = 102;


    public final int getNumber() { return value; }

    public static TIlE_LAYER1 valueOf(int value) {
      switch (value) {
        case 102: return LAYER1_TILE_BG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER1>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER1>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER1>() {
            public TIlE_LAYER1 findValueByNumber(int number) {
              return TIlE_LAYER1.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(8);
    }

    private static final TIlE_LAYER1[] VALUES = values();

    public static TIlE_LAYER1 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TIlE_LAYER1(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TIlE_LAYER1)
  }

  /**
   * Protobuf enum {@code xapp.eum.TIlE_LAYER2}
   */
  public enum TIlE_LAYER2
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LAYER2_RES_MIN = 4;</code>
     */
    LAYER2_RES_MIN(0, 4),
    /**
     * <code>LAYER2_RES_MAX = 19;</code>
     */
    LAYER2_RES_MAX(1, 19),
    /**
     * <code>LAYER2_LIGHT_RED = 25;</code>
     */
    LAYER2_LIGHT_RED(2, 25),
    /**
     * <code>LAYER2_LIGHT_BLUE = 26;</code>
     */
    LAYER2_LIGHT_BLUE(3, 26),
    /**
     * <code>LAYER2_LIGHT_GREEN = 27;</code>
     */
    LAYER2_LIGHT_GREEN(4, 27),
    /**
     * <code>LAYER2_LIGHT_WHITE = 28;</code>
     */
    LAYER2_LIGHT_WHITE(5, 28),
    /**
     * <code>LAYER2_LIGHT_GREY = 29;</code>
     */
    LAYER2_LIGHT_GREY(6, 29),
    /**
     * <code>LAYER2_TOWER_MIN_IRON = 30;</code>
     *
     * <pre>
     *铁
     * </pre>
     */
    LAYER2_TOWER_MIN_IRON(7, 30),
    /**
     * <code>LAYER2_TOWER_FSC = 38;</code>
     *
     * <pre>
     *焚尸场
     * </pre>
     */
    LAYER2_TOWER_FSC(8, 38),
    /**
     * <code>LAYER2_TOWER_MIN_MUSHROOM = 39;</code>
     *
     * <pre>
     *蘑菇
     * </pre>
     */
    LAYER2_TOWER_MIN_MUSHROOM(9, 39),
    /**
     * <code>LAYER2_TOWER_BAR = 40;</code>
     *
     * <pre>
     *酒馆
     * </pre>
     */
    LAYER2_TOWER_BAR(10, 40),
    /**
     * <code>LAYER2_TOWER_SHOP = 41;</code>
     *
     * <pre>
     *黑市
     * </pre>
     */
    LAYER2_TOWER_SHOP(11, 41),
    /**
     * <code>LAYER2_TOWER_BATTLE = 44;</code>
     *
     * <pre>
     *战场
     * </pre>
     */
    LAYER2_TOWER_BATTLE(12, 44),
    /**
     * <code>LAYER2_TOWER_TRANSLATE_DOOR = 52;</code>
     *
     * <pre>
     *传送门
     * </pre>
     */
    LAYER2_TOWER_TRANSLATE_DOOR(13, 52),
    /**
     * <code>LAYER2_TOWER_HOME = 53;</code>
     *
     * <pre>
     *老家
     * </pre>
     */
    LAYER2_TOWER_HOME(14, 53),
    /**
     * <code>LAYER2_TOWER_TRANSLATE_ROOK = 54;</code>
     *
     * <pre>
     *巨石传送门
     * </pre>
     */
    LAYER2_TOWER_TRANSLATE_ROOK(15, 54),
    /**
     * <code>LAYER2_TOWER_ENEGY = 56;</code>
     *
     * <pre>
     *能量罩
     * </pre>
     */
    LAYER2_TOWER_ENEGY(16, 56),
    ;

    /**
     * <code>LAYER2_RES_MIN = 4;</code>
     */
    public static final int LAYER2_RES_MIN_VALUE = 4;
    /**
     * <code>LAYER2_RES_MAX = 19;</code>
     */
    public static final int LAYER2_RES_MAX_VALUE = 19;
    /**
     * <code>LAYER2_LIGHT_RED = 25;</code>
     */
    public static final int LAYER2_LIGHT_RED_VALUE = 25;
    /**
     * <code>LAYER2_LIGHT_BLUE = 26;</code>
     */
    public static final int LAYER2_LIGHT_BLUE_VALUE = 26;
    /**
     * <code>LAYER2_LIGHT_GREEN = 27;</code>
     */
    public static final int LAYER2_LIGHT_GREEN_VALUE = 27;
    /**
     * <code>LAYER2_LIGHT_WHITE = 28;</code>
     */
    public static final int LAYER2_LIGHT_WHITE_VALUE = 28;
    /**
     * <code>LAYER2_LIGHT_GREY = 29;</code>
     */
    public static final int LAYER2_LIGHT_GREY_VALUE = 29;
    /**
     * <code>LAYER2_TOWER_MIN_IRON = 30;</code>
     *
     * <pre>
     *铁
     * </pre>
     */
    public static final int LAYER2_TOWER_MIN_IRON_VALUE = 30;
    /**
     * <code>LAYER2_TOWER_FSC = 38;</code>
     *
     * <pre>
     *焚尸场
     * </pre>
     */
    public static final int LAYER2_TOWER_FSC_VALUE = 38;
    /**
     * <code>LAYER2_TOWER_MIN_MUSHROOM = 39;</code>
     *
     * <pre>
     *蘑菇
     * </pre>
     */
    public static final int LAYER2_TOWER_MIN_MUSHROOM_VALUE = 39;
    /**
     * <code>LAYER2_TOWER_BAR = 40;</code>
     *
     * <pre>
     *酒馆
     * </pre>
     */
    public static final int LAYER2_TOWER_BAR_VALUE = 40;
    /**
     * <code>LAYER2_TOWER_SHOP = 41;</code>
     *
     * <pre>
     *黑市
     * </pre>
     */
    public static final int LAYER2_TOWER_SHOP_VALUE = 41;
    /**
     * <code>LAYER2_TOWER_BATTLE = 44;</code>
     *
     * <pre>
     *战场
     * </pre>
     */
    public static final int LAYER2_TOWER_BATTLE_VALUE = 44;
    /**
     * <code>LAYER2_TOWER_TRANSLATE_DOOR = 52;</code>
     *
     * <pre>
     *传送门
     * </pre>
     */
    public static final int LAYER2_TOWER_TRANSLATE_DOOR_VALUE = 52;
    /**
     * <code>LAYER2_TOWER_HOME = 53;</code>
     *
     * <pre>
     *老家
     * </pre>
     */
    public static final int LAYER2_TOWER_HOME_VALUE = 53;
    /**
     * <code>LAYER2_TOWER_TRANSLATE_ROOK = 54;</code>
     *
     * <pre>
     *巨石传送门
     * </pre>
     */
    public static final int LAYER2_TOWER_TRANSLATE_ROOK_VALUE = 54;
    /**
     * <code>LAYER2_TOWER_ENEGY = 56;</code>
     *
     * <pre>
     *能量罩
     * </pre>
     */
    public static final int LAYER2_TOWER_ENEGY_VALUE = 56;


    public final int getNumber() { return value; }

    public static TIlE_LAYER2 valueOf(int value) {
      switch (value) {
        case 4: return LAYER2_RES_MIN;
        case 19: return LAYER2_RES_MAX;
        case 25: return LAYER2_LIGHT_RED;
        case 26: return LAYER2_LIGHT_BLUE;
        case 27: return LAYER2_LIGHT_GREEN;
        case 28: return LAYER2_LIGHT_WHITE;
        case 29: return LAYER2_LIGHT_GREY;
        case 30: return LAYER2_TOWER_MIN_IRON;
        case 38: return LAYER2_TOWER_FSC;
        case 39: return LAYER2_TOWER_MIN_MUSHROOM;
        case 40: return LAYER2_TOWER_BAR;
        case 41: return LAYER2_TOWER_SHOP;
        case 44: return LAYER2_TOWER_BATTLE;
        case 52: return LAYER2_TOWER_TRANSLATE_DOOR;
        case 53: return LAYER2_TOWER_HOME;
        case 54: return LAYER2_TOWER_TRANSLATE_ROOK;
        case 56: return LAYER2_TOWER_ENEGY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER2>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER2>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TIlE_LAYER2>() {
            public TIlE_LAYER2 findValueByNumber(int number) {
              return TIlE_LAYER2.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(9);
    }

    private static final TIlE_LAYER2[] VALUES = values();

    public static TIlE_LAYER2 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TIlE_LAYER2(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TIlE_LAYER2)
  }

  /**
   * Protobuf enum {@code xapp.eum.ITEM_DEFINE}
   */
  public enum ITEM_DEFINE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ITEM_ENEGY = 75;</code>
     *
     * <pre>
     *电池
     * </pre>
     */
    ITEM_ENEGY(0, 75),
    ;

    /**
     * <code>ITEM_ENEGY = 75;</code>
     *
     * <pre>
     *电池
     * </pre>
     */
    public static final int ITEM_ENEGY_VALUE = 75;


    public final int getNumber() { return value; }

    public static ITEM_DEFINE valueOf(int value) {
      switch (value) {
        case 75: return ITEM_ENEGY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ITEM_DEFINE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ITEM_DEFINE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ITEM_DEFINE>() {
            public ITEM_DEFINE findValueByNumber(int number) {
              return ITEM_DEFINE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(10);
    }

    private static final ITEM_DEFINE[] VALUES = values();

    public static ITEM_DEFINE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ITEM_DEFINE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.ITEM_DEFINE)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_ACH}
   */
  public enum TYPE_ACH
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACH_WAJUE = 1;</code>
     *
     * <pre>
     *挖掘
     * </pre>
     */
    ACH_WAJUE(0, 1),
    /**
     * <code>ACH_JIAOYI = 2;</code>
     *
     * <pre>
     *交易
     * </pre>
     */
    ACH_JIAOYI(1, 2),
    /**
     * <code>ACH_XUNLIAN = 3;</code>
     *
     * <pre>
     *训练
     * </pre>
     */
    ACH_XUNLIAN(2, 3),
    /**
     * <code>ACH_BUCHONG = 4;</code>
     *
     * <pre>
     *补充电池
     * </pre>
     */
    ACH_BUCHONG(3, 4),
    /**
     * <code>ACH_XIDE = 5;</code>
     *
     * <pre>
     *习得
     * </pre>
     */
    ACH_XIDE(4, 5),
    /**
     * <code>ACH_JISHA = 6;</code>
     *
     * <pre>
     *击杀
     * </pre>
     */
    ACH_JISHA(5, 6),
    /**
     * <code>ACH_KAICAI = 7;</code>
     *
     * <pre>
     *开采
     * </pre>
     */
    ACH_KAICAI(6, 7),
    /**
     * <code>ACH_FUHUO = 8;</code>
     *
     * <pre>
     *复活
     * </pre>
     */
    ACH_FUHUO(7, 8),
    /**
     * <code>ACH_DITU = 9;</code>
     *
     * <pre>
     *完成地图
     * </pre>
     */
    ACH_DITU(8, 9),
    /**
     * <code>ACH_SHASI = 10;</code>
     *
     * <pre>
     *杀死数量
     * </pre>
     */
    ACH_SHASI(9, 10),
    /**
     * <code>ACH_BUJIZHAN = 11;</code>
     *
     * <pre>
     *建立补给站
     * </pre>
     */
    ACH_BUJIZHAN(10, 11),
    /**
     * <code>ACH_BASE = 12;</code>
     *
     * <pre>
     *建造建筑
     * </pre>
     */
    ACH_BASE(11, 12),
    /**
     * <code>ACH_LEADER = 13;</code>
     *
     * <pre>
     *新手引导
     * </pre>
     */
    ACH_LEADER(12, 13),
    /**
     * <code>ACH_DUBO = 14;</code>
     *
     * <pre>
     *赌博
     * </pre>
     */
    ACH_DUBO(13, 14),
    ;

    /**
     * <code>ACH_WAJUE = 1;</code>
     *
     * <pre>
     *挖掘
     * </pre>
     */
    public static final int ACH_WAJUE_VALUE = 1;
    /**
     * <code>ACH_JIAOYI = 2;</code>
     *
     * <pre>
     *交易
     * </pre>
     */
    public static final int ACH_JIAOYI_VALUE = 2;
    /**
     * <code>ACH_XUNLIAN = 3;</code>
     *
     * <pre>
     *训练
     * </pre>
     */
    public static final int ACH_XUNLIAN_VALUE = 3;
    /**
     * <code>ACH_BUCHONG = 4;</code>
     *
     * <pre>
     *补充电池
     * </pre>
     */
    public static final int ACH_BUCHONG_VALUE = 4;
    /**
     * <code>ACH_XIDE = 5;</code>
     *
     * <pre>
     *习得
     * </pre>
     */
    public static final int ACH_XIDE_VALUE = 5;
    /**
     * <code>ACH_JISHA = 6;</code>
     *
     * <pre>
     *击杀
     * </pre>
     */
    public static final int ACH_JISHA_VALUE = 6;
    /**
     * <code>ACH_KAICAI = 7;</code>
     *
     * <pre>
     *开采
     * </pre>
     */
    public static final int ACH_KAICAI_VALUE = 7;
    /**
     * <code>ACH_FUHUO = 8;</code>
     *
     * <pre>
     *复活
     * </pre>
     */
    public static final int ACH_FUHUO_VALUE = 8;
    /**
     * <code>ACH_DITU = 9;</code>
     *
     * <pre>
     *完成地图
     * </pre>
     */
    public static final int ACH_DITU_VALUE = 9;
    /**
     * <code>ACH_SHASI = 10;</code>
     *
     * <pre>
     *杀死数量
     * </pre>
     */
    public static final int ACH_SHASI_VALUE = 10;
    /**
     * <code>ACH_BUJIZHAN = 11;</code>
     *
     * <pre>
     *建立补给站
     * </pre>
     */
    public static final int ACH_BUJIZHAN_VALUE = 11;
    /**
     * <code>ACH_BASE = 12;</code>
     *
     * <pre>
     *建造建筑
     * </pre>
     */
    public static final int ACH_BASE_VALUE = 12;
    /**
     * <code>ACH_LEADER = 13;</code>
     *
     * <pre>
     *新手引导
     * </pre>
     */
    public static final int ACH_LEADER_VALUE = 13;
    /**
     * <code>ACH_DUBO = 14;</code>
     *
     * <pre>
     *赌博
     * </pre>
     */
    public static final int ACH_DUBO_VALUE = 14;


    public final int getNumber() { return value; }

    public static TYPE_ACH valueOf(int value) {
      switch (value) {
        case 1: return ACH_WAJUE;
        case 2: return ACH_JIAOYI;
        case 3: return ACH_XUNLIAN;
        case 4: return ACH_BUCHONG;
        case 5: return ACH_XIDE;
        case 6: return ACH_JISHA;
        case 7: return ACH_KAICAI;
        case 8: return ACH_FUHUO;
        case 9: return ACH_DITU;
        case 10: return ACH_SHASI;
        case 11: return ACH_BUJIZHAN;
        case 12: return ACH_BASE;
        case 13: return ACH_LEADER;
        case 14: return ACH_DUBO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_ACH>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_ACH>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_ACH>() {
            public TYPE_ACH findValueByNumber(int number) {
              return TYPE_ACH.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(11);
    }

    private static final TYPE_ACH[] VALUES = values();

    public static TYPE_ACH valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_ACH(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_ACH)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_ITEM}
   */
  public enum TYPE_ITEM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TYPE_WAJUE_NUM = 1;</code>
     *
     * <pre>
     *挖掘数量
     * </pre>
     */
    TYPE_WAJUE_NUM(0, 1),
    /**
     * <code>TYPE_BEIBAO = 2;</code>
     *
     * <pre>
     *背包容量
     * </pre>
     */
    TYPE_BEIBAO(1, 2),
    /**
     * <code>TYPE_DUIWU = 3;</code>
     *
     * <pre>
     *军队上限
     * </pre>
     */
    TYPE_DUIWU(2, 3),
    /**
     * <code>TYPE_CAIJI = 4;</code>
     *
     * <pre>
     *等级   采集
     * </pre>
     */
    TYPE_CAIJI(3, 4),
    /**
     * <code>TYPE_SHIYE = 5;</code>
     *
     * <pre>
     *视野探索范围
     * </pre>
     */
    TYPE_SHIYE(4, 5),
    /**
     * <code>TYPE_MIANBAO = 6;</code>
     *
     * <pre>
     *电池 补充的  生命值
     * </pre>
     */
    TYPE_MIANBAO(5, 6),
    ;

    /**
     * <code>TYPE_WAJUE_NUM = 1;</code>
     *
     * <pre>
     *挖掘数量
     * </pre>
     */
    public static final int TYPE_WAJUE_NUM_VALUE = 1;
    /**
     * <code>TYPE_BEIBAO = 2;</code>
     *
     * <pre>
     *背包容量
     * </pre>
     */
    public static final int TYPE_BEIBAO_VALUE = 2;
    /**
     * <code>TYPE_DUIWU = 3;</code>
     *
     * <pre>
     *军队上限
     * </pre>
     */
    public static final int TYPE_DUIWU_VALUE = 3;
    /**
     * <code>TYPE_CAIJI = 4;</code>
     *
     * <pre>
     *等级   采集
     * </pre>
     */
    public static final int TYPE_CAIJI_VALUE = 4;
    /**
     * <code>TYPE_SHIYE = 5;</code>
     *
     * <pre>
     *视野探索范围
     * </pre>
     */
    public static final int TYPE_SHIYE_VALUE = 5;
    /**
     * <code>TYPE_MIANBAO = 6;</code>
     *
     * <pre>
     *电池 补充的  生命值
     * </pre>
     */
    public static final int TYPE_MIANBAO_VALUE = 6;


    public final int getNumber() { return value; }

    public static TYPE_ITEM valueOf(int value) {
      switch (value) {
        case 1: return TYPE_WAJUE_NUM;
        case 2: return TYPE_BEIBAO;
        case 3: return TYPE_DUIWU;
        case 4: return TYPE_CAIJI;
        case 5: return TYPE_SHIYE;
        case 6: return TYPE_MIANBAO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_ITEM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_ITEM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_ITEM>() {
            public TYPE_ITEM findValueByNumber(int number) {
              return TYPE_ITEM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(12);
    }

    private static final TYPE_ITEM[] VALUES = values();

    public static TYPE_ITEM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_ITEM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_ITEM)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_MAIN_ID}
   */
  public enum TYPE_MAIN_ID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ID_PUB = 1;</code>
     */
    ID_PUB(0, 1),
    /**
     * <code>ID_VILLAGE = 6;</code>
     */
    ID_VILLAGE(1, 6),
    /**
     * <code>ID_BASE = 3;</code>
     */
    ID_BASE(2, 3),
    /**
     * <code>ID_EXCHANGE = 4;</code>
     */
    ID_EXCHANGE(3, 4),
    /**
     * <code>ID_EQUIPMENT = 5;</code>
     */
    ID_EQUIPMENT(4, 5),
    /**
     * <code>ID_BARRACKS = 2;</code>
     */
    ID_BARRACKS(5, 2),
    /**
     * <code>ID_SHOP = 7;</code>
     */
    ID_SHOP(6, 7),
    /**
     * <code>ID_ACHIEVEMENT = 8;</code>
     */
    ID_ACHIEVEMENT(7, 8),
    /**
     * <code>ID_WAJUE = 9;</code>
     *
     * <pre>
     *挖掘 按钮//主按钮
     * </pre>
     */
    ID_WAJUE(8, 9),
    /**
     * <code>id_task = 10;</code>
     *
     * <pre>
     *任务 按钮
     * </pre>
     */
    id_task(9, 10),
    ;

    /**
     * <code>ID_PUB = 1;</code>
     */
    public static final int ID_PUB_VALUE = 1;
    /**
     * <code>ID_VILLAGE = 6;</code>
     */
    public static final int ID_VILLAGE_VALUE = 6;
    /**
     * <code>ID_BASE = 3;</code>
     */
    public static final int ID_BASE_VALUE = 3;
    /**
     * <code>ID_EXCHANGE = 4;</code>
     */
    public static final int ID_EXCHANGE_VALUE = 4;
    /**
     * <code>ID_EQUIPMENT = 5;</code>
     */
    public static final int ID_EQUIPMENT_VALUE = 5;
    /**
     * <code>ID_BARRACKS = 2;</code>
     */
    public static final int ID_BARRACKS_VALUE = 2;
    /**
     * <code>ID_SHOP = 7;</code>
     */
    public static final int ID_SHOP_VALUE = 7;
    /**
     * <code>ID_ACHIEVEMENT = 8;</code>
     */
    public static final int ID_ACHIEVEMENT_VALUE = 8;
    /**
     * <code>ID_WAJUE = 9;</code>
     *
     * <pre>
     *挖掘 按钮//主按钮
     * </pre>
     */
    public static final int ID_WAJUE_VALUE = 9;
    /**
     * <code>id_task = 10;</code>
     *
     * <pre>
     *任务 按钮
     * </pre>
     */
    public static final int id_task_VALUE = 10;


    public final int getNumber() { return value; }

    public static TYPE_MAIN_ID valueOf(int value) {
      switch (value) {
        case 1: return ID_PUB;
        case 6: return ID_VILLAGE;
        case 3: return ID_BASE;
        case 4: return ID_EXCHANGE;
        case 5: return ID_EQUIPMENT;
        case 2: return ID_BARRACKS;
        case 7: return ID_SHOP;
        case 8: return ID_ACHIEVEMENT;
        case 9: return ID_WAJUE;
        case 10: return id_task;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_MAIN_ID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_MAIN_ID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_MAIN_ID>() {
            public TYPE_MAIN_ID findValueByNumber(int number) {
              return TYPE_MAIN_ID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(13);
    }

    private static final TYPE_MAIN_ID[] VALUES = values();

    public static TYPE_MAIN_ID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_MAIN_ID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_MAIN_ID)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_BTN_ID_VILLAGE}
   */
  public enum TYPE_BTN_ID_VILLAGE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ID_LEFT_VILLAGE = 1;</code>
     */
    ID_LEFT_VILLAGE(0, 1),
    /**
     * <code>ID_KAICAI = 2;</code>
     *
     * <pre>
     *开采//主按钮
     * </pre>
     */
    ID_KAICAI(1, 2),
    /**
     * <code>ID_JIAHAO_VILLAGE = 3;</code>
     */
    ID_JIAHAO_VILLAGE(2, 3),
    ;

    /**
     * <code>ID_LEFT_VILLAGE = 1;</code>
     */
    public static final int ID_LEFT_VILLAGE_VALUE = 1;
    /**
     * <code>ID_KAICAI = 2;</code>
     *
     * <pre>
     *开采//主按钮
     * </pre>
     */
    public static final int ID_KAICAI_VALUE = 2;
    /**
     * <code>ID_JIAHAO_VILLAGE = 3;</code>
     */
    public static final int ID_JIAHAO_VILLAGE_VALUE = 3;


    public final int getNumber() { return value; }

    public static TYPE_BTN_ID_VILLAGE valueOf(int value) {
      switch (value) {
        case 1: return ID_LEFT_VILLAGE;
        case 2: return ID_KAICAI;
        case 3: return ID_JIAHAO_VILLAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_BTN_ID_VILLAGE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_BTN_ID_VILLAGE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_BTN_ID_VILLAGE>() {
            public TYPE_BTN_ID_VILLAGE findValueByNumber(int number) {
              return TYPE_BTN_ID_VILLAGE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(14);
    }

    private static final TYPE_BTN_ID_VILLAGE[] VALUES = values();

    public static TYPE_BTN_ID_VILLAGE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_BTN_ID_VILLAGE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_BTN_ID_VILLAGE)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_BTN_ID_BARRACKS}
   *
   * <pre>
   *ID_LEFT_BARRACKS =1;//左侧 离开 按钮
   *ID_ZHAOMU =2;//招募//主按钮
   * </pre>
   */
  public enum TYPE_BTN_ID_BARRACKS
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ID_BARRACKS_LEFT = 1;</code>
     *
     * <pre>
     *左侧 离开按钮
     * </pre>
     */
    ID_BARRACKS_LEFT(0, 1),
    /**
     * <code>ID_BARRACKS_RIGHT = 2;</code>
     *
     * <pre>
     *右侧 离开按钮
     * </pre>
     */
    ID_BARRACKS_RIGHT(1, 2),
    /**
     * <code>ID_BARRACKS_ARMY = 3;</code>
     *
     * <pre>
     *军队
     * </pre>
     */
    ID_BARRACKS_ARMY(2, 3),
    /**
     * <code>ID_BARRACKS_ZHAOMU = 4;</code>
     *
     * <pre>
     *招募 按钮
     * </pre>
     */
    ID_BARRACKS_ZHAOMU(3, 4),
    /**
     * <code>ID_BARRACKS_TEAM = 5;</code>
     *
     * <pre>
     *战队
     * </pre>
     */
    ID_BARRACKS_TEAM(4, 5),
    /**
     * <code>ID_BARRACKS_TANSUO = 6;</code>
     *
     * <pre>
     *探索 按钮
     * </pre>
     */
    ID_BARRACKS_TANSUO(5, 6),
    ;

    /**
     * <code>ID_BARRACKS_LEFT = 1;</code>
     *
     * <pre>
     *左侧 离开按钮
     * </pre>
     */
    public static final int ID_BARRACKS_LEFT_VALUE = 1;
    /**
     * <code>ID_BARRACKS_RIGHT = 2;</code>
     *
     * <pre>
     *右侧 离开按钮
     * </pre>
     */
    public static final int ID_BARRACKS_RIGHT_VALUE = 2;
    /**
     * <code>ID_BARRACKS_ARMY = 3;</code>
     *
     * <pre>
     *军队
     * </pre>
     */
    public static final int ID_BARRACKS_ARMY_VALUE = 3;
    /**
     * <code>ID_BARRACKS_ZHAOMU = 4;</code>
     *
     * <pre>
     *招募 按钮
     * </pre>
     */
    public static final int ID_BARRACKS_ZHAOMU_VALUE = 4;
    /**
     * <code>ID_BARRACKS_TEAM = 5;</code>
     *
     * <pre>
     *战队
     * </pre>
     */
    public static final int ID_BARRACKS_TEAM_VALUE = 5;
    /**
     * <code>ID_BARRACKS_TANSUO = 6;</code>
     *
     * <pre>
     *探索 按钮
     * </pre>
     */
    public static final int ID_BARRACKS_TANSUO_VALUE = 6;


    public final int getNumber() { return value; }

    public static TYPE_BTN_ID_BARRACKS valueOf(int value) {
      switch (value) {
        case 1: return ID_BARRACKS_LEFT;
        case 2: return ID_BARRACKS_RIGHT;
        case 3: return ID_BARRACKS_ARMY;
        case 4: return ID_BARRACKS_ZHAOMU;
        case 5: return ID_BARRACKS_TEAM;
        case 6: return ID_BARRACKS_TANSUO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_BTN_ID_BARRACKS>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_BTN_ID_BARRACKS>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_BTN_ID_BARRACKS>() {
            public TYPE_BTN_ID_BARRACKS findValueByNumber(int number) {
              return TYPE_BTN_ID_BARRACKS.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(15);
    }

    private static final TYPE_BTN_ID_BARRACKS[] VALUES = values();

    public static TYPE_BTN_ID_BARRACKS valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_BTN_ID_BARRACKS(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_BTN_ID_BARRACKS)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_SHOP}
   */
  public enum TYPE_SHOP
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SHOP_ARMY = 1;</code>
     */
    SHOP_ARMY(0, 1),
    /**
     * <code>SHOP_BUILD = 2;</code>
     *
     * <pre>
     *开采
     * </pre>
     */
    SHOP_BUILD(1, 2),
    /**
     * <code>SHOP_TALENT = 3;</code>
     */
    SHOP_TALENT(2, 3),
    /**
     * <code>SHOP_MAP = 4;</code>
     */
    SHOP_MAP(3, 4),
    /**
     * <code>SHOP_ITEM = 5;</code>
     */
    SHOP_ITEM(4, 5),
    /**
     * <code>SHOP_DATA = 6;</code>
     */
    SHOP_DATA(5, 6),
    ;

    /**
     * <code>SHOP_ARMY = 1;</code>
     */
    public static final int SHOP_ARMY_VALUE = 1;
    /**
     * <code>SHOP_BUILD = 2;</code>
     *
     * <pre>
     *开采
     * </pre>
     */
    public static final int SHOP_BUILD_VALUE = 2;
    /**
     * <code>SHOP_TALENT = 3;</code>
     */
    public static final int SHOP_TALENT_VALUE = 3;
    /**
     * <code>SHOP_MAP = 4;</code>
     */
    public static final int SHOP_MAP_VALUE = 4;
    /**
     * <code>SHOP_ITEM = 5;</code>
     */
    public static final int SHOP_ITEM_VALUE = 5;
    /**
     * <code>SHOP_DATA = 6;</code>
     */
    public static final int SHOP_DATA_VALUE = 6;


    public final int getNumber() { return value; }

    public static TYPE_SHOP valueOf(int value) {
      switch (value) {
        case 1: return SHOP_ARMY;
        case 2: return SHOP_BUILD;
        case 3: return SHOP_TALENT;
        case 4: return SHOP_MAP;
        case 5: return SHOP_ITEM;
        case 6: return SHOP_DATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_SHOP>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_SHOP>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_SHOP>() {
            public TYPE_SHOP findValueByNumber(int number) {
              return TYPE_SHOP.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(16);
    }

    private static final TYPE_SHOP[] VALUES = values();

    public static TYPE_SHOP valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_SHOP(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_SHOP)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_TALENT}
   */
  public enum TYPE_TALENT
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TALENT_SHANBI = 1;</code>
     */
    TALENT_SHANBI(0, 1),
    /**
     * <code>TALENT_MINGZHONG = 2;</code>
     */
    TALENT_MINGZHONG(1, 2),
    /**
     * <code>TALENT_XIAOHAO = 3;</code>
     */
    TALENT_XIAOHAO(2, 3),
    /**
     * <code>TALENT_HP = 4;</code>
     */
    TALENT_HP(3, 4),
    /**
     * <code>TALENT_ATTACK = 5;</code>
     */
    TALENT_ATTACK(4, 5),
    /**
     * <code>TALENT_ATTACKED = 6;</code>
     */
    TALENT_ATTACKED(5, 6),
    /**
     * <code>TALENT_SPEED = 7;</code>
     */
    TALENT_SPEED(6, 7),
    /**
     * <code>TALENT_BAOJI_LV = 8;</code>
     */
    TALENT_BAOJI_LV(7, 8),
    /**
     * <code>TALENT_BAOJI_ATTACK = 9;</code>
     */
    TALENT_BAOJI_ATTACK(8, 9),
    ;

    /**
     * <code>TALENT_SHANBI = 1;</code>
     */
    public static final int TALENT_SHANBI_VALUE = 1;
    /**
     * <code>TALENT_MINGZHONG = 2;</code>
     */
    public static final int TALENT_MINGZHONG_VALUE = 2;
    /**
     * <code>TALENT_XIAOHAO = 3;</code>
     */
    public static final int TALENT_XIAOHAO_VALUE = 3;
    /**
     * <code>TALENT_HP = 4;</code>
     */
    public static final int TALENT_HP_VALUE = 4;
    /**
     * <code>TALENT_ATTACK = 5;</code>
     */
    public static final int TALENT_ATTACK_VALUE = 5;
    /**
     * <code>TALENT_ATTACKED = 6;</code>
     */
    public static final int TALENT_ATTACKED_VALUE = 6;
    /**
     * <code>TALENT_SPEED = 7;</code>
     */
    public static final int TALENT_SPEED_VALUE = 7;
    /**
     * <code>TALENT_BAOJI_LV = 8;</code>
     */
    public static final int TALENT_BAOJI_LV_VALUE = 8;
    /**
     * <code>TALENT_BAOJI_ATTACK = 9;</code>
     */
    public static final int TALENT_BAOJI_ATTACK_VALUE = 9;


    public final int getNumber() { return value; }

    public static TYPE_TALENT valueOf(int value) {
      switch (value) {
        case 1: return TALENT_SHANBI;
        case 2: return TALENT_MINGZHONG;
        case 3: return TALENT_XIAOHAO;
        case 4: return TALENT_HP;
        case 5: return TALENT_ATTACK;
        case 6: return TALENT_ATTACKED;
        case 7: return TALENT_SPEED;
        case 8: return TALENT_BAOJI_LV;
        case 9: return TALENT_BAOJI_ATTACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_TALENT>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_TALENT>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_TALENT>() {
            public TYPE_TALENT findValueByNumber(int number) {
              return TYPE_TALENT.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(17);
    }

    private static final TYPE_TALENT[] VALUES = values();

    public static TYPE_TALENT valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_TALENT(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_TALENT)
  }

  /**
   * Protobuf enum {@code xapp.eum.TYPE_DATA}
   */
  public enum TYPE_DATA
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA_WAJUE = 1;</code>
     */
    DATA_WAJUE(0, 1),
    /**
     * <code>DATA_KAICAI = 2;</code>
     */
    DATA_KAICAI(1, 2),
    /**
     * <code>DATA_TANSUO = 3;</code>
     */
    DATA_TANSUO(2, 3),
    /**
     * <code>DATA_LUCK = 4;</code>
     */
    DATA_LUCK(3, 4),
    /**
     * <code>DATA_POINT = 5;</code>
     */
    DATA_POINT(4, 5),
    /**
     * <code>DATA_TALENT = 6;</code>
     */
    DATA_TALENT(5, 6),
    /**
     * <code>DATA_BUJI = 7;</code>
     */
    DATA_BUJI(6, 7),
    /**
     * <code>DATA_DUBO = 8;</code>
     */
    DATA_DUBO(7, 8),
    /**
     * <code>DATA_JIAOYI = 9;</code>
     */
    DATA_JIAOYI(8, 9),
    /**
     * <code>DATA_JIXIECANG = 10;</code>
     */
    DATA_JIXIECANG(9, 10),
    /**
     * <code>DATA_QINGLI = 11;</code>
     *
     * <pre>
     *清理
     * </pre>
     */
    DATA_QINGLI(10, 11),
    /**
     * <code>DATA_WIN = 12;</code>
     *
     * <pre>
     *战斗胜利
     * </pre>
     */
    DATA_WIN(11, 12),
    /**
     * <code>DATA_FANGWEN = 13;</code>
     *
     * <pre>
     *访问
     * </pre>
     */
    DATA_FANGWEN(12, 13),
    ;

    /**
     * <code>DATA_WAJUE = 1;</code>
     */
    public static final int DATA_WAJUE_VALUE = 1;
    /**
     * <code>DATA_KAICAI = 2;</code>
     */
    public static final int DATA_KAICAI_VALUE = 2;
    /**
     * <code>DATA_TANSUO = 3;</code>
     */
    public static final int DATA_TANSUO_VALUE = 3;
    /**
     * <code>DATA_LUCK = 4;</code>
     */
    public static final int DATA_LUCK_VALUE = 4;
    /**
     * <code>DATA_POINT = 5;</code>
     */
    public static final int DATA_POINT_VALUE = 5;
    /**
     * <code>DATA_TALENT = 6;</code>
     */
    public static final int DATA_TALENT_VALUE = 6;
    /**
     * <code>DATA_BUJI = 7;</code>
     */
    public static final int DATA_BUJI_VALUE = 7;
    /**
     * <code>DATA_DUBO = 8;</code>
     */
    public static final int DATA_DUBO_VALUE = 8;
    /**
     * <code>DATA_JIAOYI = 9;</code>
     */
    public static final int DATA_JIAOYI_VALUE = 9;
    /**
     * <code>DATA_JIXIECANG = 10;</code>
     */
    public static final int DATA_JIXIECANG_VALUE = 10;
    /**
     * <code>DATA_QINGLI = 11;</code>
     *
     * <pre>
     *清理
     * </pre>
     */
    public static final int DATA_QINGLI_VALUE = 11;
    /**
     * <code>DATA_WIN = 12;</code>
     *
     * <pre>
     *战斗胜利
     * </pre>
     */
    public static final int DATA_WIN_VALUE = 12;
    /**
     * <code>DATA_FANGWEN = 13;</code>
     *
     * <pre>
     *访问
     * </pre>
     */
    public static final int DATA_FANGWEN_VALUE = 13;


    public final int getNumber() { return value; }

    public static TYPE_DATA valueOf(int value) {
      switch (value) {
        case 1: return DATA_WAJUE;
        case 2: return DATA_KAICAI;
        case 3: return DATA_TANSUO;
        case 4: return DATA_LUCK;
        case 5: return DATA_POINT;
        case 6: return DATA_TALENT;
        case 7: return DATA_BUJI;
        case 8: return DATA_DUBO;
        case 9: return DATA_JIAOYI;
        case 10: return DATA_JIXIECANG;
        case 11: return DATA_QINGLI;
        case 12: return DATA_WIN;
        case 13: return DATA_FANGWEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE_DATA>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TYPE_DATA>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE_DATA>() {
            public TYPE_DATA findValueByNumber(int number) {
              return TYPE_DATA.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBEnum.getDescriptor().getEnumTypes().get(18);
    }

    private static final TYPE_DATA[] VALUES = values();

    public static TYPE_DATA valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE_DATA(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.eum.TYPE_DATA)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\teum.proto\022\010xapp.eum*G\n\013MOVING_TYPE\022\022\n\016" +
      "MOVING_TO_LEFT\020\001\022\023\n\017MOVING_TO_RIGHT\020\002\022\017\n" +
      "\013MOVING_NONE\020\003*\364\002\n\nENUM_Sound\022\014\n\010E_Sbeid" +
      "a\020\001\022\016\n\nE_Sbeidasi\020\002\022\014\n\010E_Scaiji\020\003\022\017\n\013E_S" +
      "dianneng\020\004\022\r\n\tE_Sgongji\020\005\022\t\n\005E_Spk\020\006\022\017\n\013" +
      "E_Suianjian\020\007\022\r\n\tE_Swajue1\020\010\022\024\n\020E_Swanch" +
      "engrenwu\020\t\022\016\n\nE_Syaosai4\020\n\022\020\n\014E_Syaosaiu" +
      "i2\020\013\022\022\n\016E_Szhuuianjian\020\014\022\r\n\tE_Szoulu1\020\r\022" +
      "\r\n\tE_Szuoyou\020\016\022\017\n\013E_Sguaiwusi\020\017\022\013\n\007E_Sdu" +
      "bo\020\020\022\r\n\tE_Stianfu\020\021\022\022\n\016E_Sziyuanbugou\020\022\022",
      "\031\n\025E_Sshengtaiyuanjiahao\020\023\022\034\n\030E_Schengji" +
      "ushengjitubiao\020\024\022\013\n\007E_Szimu\020\025*\366\002\n\014ENUM_U" +
      "I_PAGE\022\014\n\010E_UImain\020\001\022\017\n\013E_UIvillage\020\002\022\013\n" +
      "\007E_UIpub\020\003\022\013\n\007E_UIbag\020\004\022\016\n\nE_UIbattle\020\005\022" +
      "\013\n\007E_UIend\020\006\022\013\n\007E_UImap\020\007\022\014\n\010E_UIbase\020\010\022" +
      "\020\n\014E_UIexchange\020\t\022\021\n\rE_UIequipment\020\n\022\020\n\014" +
      "E_UIbarracks\020\013\022\013\n\007E_UIset\020\014\022\017\n\013E_UIlanua" +
      "ge\020\r\022\017\n\013E_UIloading\020\016\022\014\n\010E_UIshop\020\017\022\020\n\014E" +
      "_UIRecharge\020\020\022\023\n\017E_UIAchievement\020\021\022\016\n\nE_" +
      "UITalent\020\022\022\025\n\021E_UIBattleMessage\020\023\022\021\n\rE_U",
      "Itranslate\020\024\022\014\n\010E_UITask\020\025\022\022\n\r__E_UIPerL" +
      "oad\020\350\007*\262\003\n\rENUM_UI_EVENT\022\023\n\017event_barry_" +
      "low\020\001\022\016\n\nevent_base\020\002\022\022\n\016event_exchange\020" +
      "\003\022\023\n\017event_equipment\020\004\022\022\n\016event_barracks" +
      "\020\005\022\021\n\revent_village\020\006\022\022\n\016event_village2\020" +
      "\007\022\025\n\021event_achievement\020\010\022\r\n\tevent_pub\020\t\022" +
      "\020\n\014event_talent\020\n\022\016\n\nevent_luck\020\013\022\016\n\neve" +
      "nt_shop\020\014\022\017\n\013event_base2\020\r\022\016\n\nevent_buji" +
      "\020\016\022\020\n\014event_fenshi\020\017\022\016\n\nevent_moku\020\020\022\021\n\r" +
      "event_shengji\020\021\022\023\n\017event_zhanchang\020\022\022\023\n\017",
      "event_introduce\020\031\022\026\n\022event_battle_alert\020" +
      "\032\022\023\n\017event_first_win\020\037\022\023\n\017event_open_doo" +
      "r\020!*\275\001\n\013ATTACK_TYPE\022\r\n\tAT_NORMAL\020\001\022\r\n\tAT" +
      "_BLOODY\020\002\022\022\n\016AT_JUST_HEALTH\020\003\022\024\n\020AT_ATTA" +
      "CK_HEALTH\020\004\022\024\n\020AT_ATTACK_POISON\020\005\022\021\n\rAT_" +
      "ATTACK_LOW\020\006\022\024\n\020AT_HEALTH_BLOODY\020\007\022\024\n\020AT" +
      "_HEALTH_POISON\020\010\022\021\n\rAT_HEALTH_LOW\020\t*l\n\023M" +
      "ONSTER_ATTACK_TYPE\022\r\n\tMA_NORMAL\020\001\022\016\n\nMA_" +
      "BURNING\020\002\022\r\n\tMA_SHIELD\020\003\022\014\n\010MA_ALIVE\020\004\022\n" +
      "\n\006MA_ICE\020\005\022\r\n\tMA_HEALTH\020\006*$\n\013TIlE_LAYER3",
      "\022\025\n\021LAYER3_MARK_BEGIN\020Q*9\n\013TIlE_DEFINE\022\024" +
      "\n\020LAYER2_TOWER_MIN\020\036\022\024\n\020LAYER2_TOWER_MAX" +
      "\0208*!\n\013TIlE_LAYER1\022\022\n\016LAYER1_TILE_BG\020f*\260\003" +
      "\n\013TIlE_LAYER2\022\022\n\016LAYER2_RES_MIN\020\004\022\022\n\016LAY" +
      "ER2_RES_MAX\020\023\022\024\n\020LAYER2_LIGHT_RED\020\031\022\025\n\021L" +
      "AYER2_LIGHT_BLUE\020\032\022\026\n\022LAYER2_LIGHT_GREEN" +
      "\020\033\022\026\n\022LAYER2_LIGHT_WHITE\020\034\022\025\n\021LAYER2_LIG" +
      "HT_GREY\020\035\022\031\n\025LAYER2_TOWER_MIN_IRON\020\036\022\024\n\020" +
      "LAYER2_TOWER_FSC\020&\022\035\n\031LAYER2_TOWER_MIN_M" +
      "USHROOM\020\'\022\024\n\020LAYER2_TOWER_BAR\020(\022\025\n\021LAYER",
      "2_TOWER_SHOP\020)\022\027\n\023LAYER2_TOWER_BATTLE\020,\022" +
      "\037\n\033LAYER2_TOWER_TRANSLATE_DOOR\0204\022\025\n\021LAYE" +
      "R2_TOWER_HOME\0205\022\037\n\033LAYER2_TOWER_TRANSLAT" +
      "E_ROOK\0206\022\026\n\022LAYER2_TOWER_ENEGY\0208*\035\n\013ITEM" +
      "_DEFINE\022\016\n\nITEM_ENEGY\020K*\342\001\n\010TYPE_ACH\022\r\n\t" +
      "ACH_WAJUE\020\001\022\016\n\nACH_JIAOYI\020\002\022\017\n\013ACH_XUNLI" +
      "AN\020\003\022\017\n\013ACH_BUCHONG\020\004\022\014\n\010ACH_XIDE\020\005\022\r\n\tA" +
      "CH_JISHA\020\006\022\016\n\nACH_KAICAI\020\007\022\r\n\tACH_FUHUO\020" +
      "\010\022\014\n\010ACH_DITU\020\t\022\r\n\tACH_SHASI\020\n\022\020\n\014ACH_BU" +
      "JIZHAN\020\013\022\014\n\010ACH_BASE\020\014\022\016\n\nACH_LEADER\020\r\022\014",
      "\n\010ACH_DUBO\020\016*r\n\tTYPE_ITEM\022\022\n\016TYPE_WAJUE_" +
      "NUM\020\001\022\017\n\013TYPE_BEIBAO\020\002\022\016\n\nTYPE_DUIWU\020\003\022\016" +
      "\n\nTYPE_CAIJI\020\004\022\016\n\nTYPE_SHIYE\020\005\022\020\n\014TYPE_M" +
      "IANBAO\020\006*\247\001\n\014TYPE_MAIN_ID\022\n\n\006ID_PUB\020\001\022\016\n" +
      "\nID_VILLAGE\020\006\022\013\n\007ID_BASE\020\003\022\017\n\013ID_EXCHANG" +
      "E\020\004\022\020\n\014ID_EQUIPMENT\020\005\022\017\n\013ID_BARRACKS\020\002\022\013" +
      "\n\007ID_SHOP\020\007\022\022\n\016ID_ACHIEVEMENT\020\010\022\014\n\010ID_WA" +
      "JUE\020\t\022\013\n\007id_task\020\n*P\n\023TYPE_BTN_ID_VILLAG" +
      "E\022\023\n\017ID_LEFT_VILLAGE\020\001\022\r\n\tID_KAICAI\020\002\022\025\n" +
      "\021ID_JIAHAO_VILLAGE\020\003*\237\001\n\024TYPE_BTN_ID_BAR",
      "RACKS\022\024\n\020ID_BARRACKS_LEFT\020\001\022\025\n\021ID_BARRAC" +
      "KS_RIGHT\020\002\022\024\n\020ID_BARRACKS_ARMY\020\003\022\026\n\022ID_B" +
      "ARRACKS_ZHAOMU\020\004\022\024\n\020ID_BARRACKS_TEAM\020\005\022\026" +
      "\n\022ID_BARRACKS_TANSUO\020\006*g\n\tTYPE_SHOP\022\r\n\tS" +
      "HOP_ARMY\020\001\022\016\n\nSHOP_BUILD\020\002\022\017\n\013SHOP_TALEN" +
      "T\020\003\022\014\n\010SHOP_MAP\020\004\022\r\n\tSHOP_ITEM\020\005\022\r\n\tSHOP" +
      "_DATA\020\006*\301\001\n\013TYPE_TALENT\022\021\n\rTALENT_SHANBI" +
      "\020\001\022\024\n\020TALENT_MINGZHONG\020\002\022\022\n\016TALENT_XIAOH" +
      "AO\020\003\022\r\n\tTALENT_HP\020\004\022\021\n\rTALENT_ATTACK\020\005\022\023" +
      "\n\017TALENT_ATTACKED\020\006\022\020\n\014TALENT_SPEED\020\007\022\023\n",
      "\017TALENT_BAOJI_LV\020\010\022\027\n\023TALENT_BAOJI_ATTAC" +
      "K\020\t*\341\001\n\tTYPE_DATA\022\016\n\nDATA_WAJUE\020\001\022\017\n\013DAT" +
      "A_KAICAI\020\002\022\017\n\013DATA_TANSUO\020\003\022\r\n\tDATA_LUCK" +
      "\020\004\022\016\n\nDATA_POINT\020\005\022\017\n\013DATA_TALENT\020\006\022\r\n\tD" +
      "ATA_BUJI\020\007\022\r\n\tDATA_DUBO\020\010\022\017\n\013DATA_JIAOYI" +
      "\020\t\022\022\n\016DATA_JIXIECANG\020\n\022\017\n\013DATA_QINGLI\020\013\022" +
      "\014\n\010DATA_WIN\020\014\022\020\n\014DATA_FANGWEN\020\rB\027\n\rcom.f" +
      "inger.pbB\006PBEnum"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
