// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: socket.proto

package com.finger.pb;

public final class PBSocket {
  private PBSocket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code xapp.socket.MessageCode}
   */
  public enum MessageCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYS_NORMAL = 1;</code>
     *
     * <pre>
     *正常的通信,非1的话就是有错误
     * </pre>
     */
    SYS_NORMAL(0, 1),
    /**
     * <code>SYS_NOT_ENOUGH_GOLD = 2;</code>
     *
     * <pre>
     *金钱不足
     * </pre>
     */
    SYS_NOT_ENOUGH_GOLD(1, 2),
    ;

    /**
     * <code>SYS_NORMAL = 1;</code>
     *
     * <pre>
     *正常的通信,非1的话就是有错误
     * </pre>
     */
    public static final int SYS_NORMAL_VALUE = 1;
    /**
     * <code>SYS_NOT_ENOUGH_GOLD = 2;</code>
     *
     * <pre>
     *金钱不足
     * </pre>
     */
    public static final int SYS_NOT_ENOUGH_GOLD_VALUE = 2;


    public final int getNumber() { return value; }

    public static MessageCode valueOf(int value) {
      switch (value) {
        case 1: return SYS_NORMAL;
        case 2: return SYS_NOT_ENOUGH_GOLD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageCode>() {
            public MessageCode findValueByNumber(int number) {
              return MessageCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBSocket.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageCode[] VALUES = values();

    public static MessageCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.socket.MessageCode)
  }

  /**
   * Protobuf enum {@code xapp.socket.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_HEART_BEAT = 100001;</code>
     */
    MSG_HEART_BEAT(0, 100001),
    ;

    /**
     * <code>MSG_HEART_BEAT = 100001;</code>
     */
    public static final int MSG_HEART_BEAT_VALUE = 100001;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 100001: return MSG_HEART_BEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.finger.pb.PBSocket.getDescriptor().getEnumTypes().get(1);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:xapp.socket.MessageType)
  }

  public interface CMsgBaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes msghead = 1;
    /**
     * <code>required bytes msghead = 1;</code>
     *
     * <pre>
     *存放msgHead
     * </pre>
     */
    boolean hasMsghead();
    /**
     * <code>required bytes msghead = 1;</code>
     *
     * <pre>
     *存放msgHead
     * </pre>
     */
    com.google.protobuf.ByteString getMsghead();

    // optional bytes msgbody = 2;
    /**
     * <code>optional bytes msgbody = 2;</code>
     *
     * <pre>
     *存放某个message
     * </pre>
     */
    boolean hasMsgbody();
    /**
     * <code>optional bytes msgbody = 2;</code>
     *
     * <pre>
     *存放某个message
     * </pre>
     */
    com.google.protobuf.ByteString getMsgbody();
  }
  /**
   * Protobuf type {@code xapp.socket.CMsgBase}
   */
  public static final class CMsgBase extends
      com.google.protobuf.GeneratedMessage
      implements CMsgBaseOrBuilder {
    // Use CMsgBase.newBuilder() to construct.
    private CMsgBase(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CMsgBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CMsgBase defaultInstance;
    public static CMsgBase getDefaultInstance() {
      return defaultInstance;
    }

    public CMsgBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CMsgBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msghead_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgbody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finger.pb.PBSocket.CMsgBase.class, com.finger.pb.PBSocket.CMsgBase.Builder.class);
    }

    public static com.google.protobuf.Parser<CMsgBase> PARSER =
        new com.google.protobuf.AbstractParser<CMsgBase>() {
      public CMsgBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CMsgBase(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CMsgBase> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes msghead = 1;
    public static final int MSGHEAD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString msghead_;
    /**
     * <code>required bytes msghead = 1;</code>
     *
     * <pre>
     *存放msgHead
     * </pre>
     */
    public boolean hasMsghead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes msghead = 1;</code>
     *
     * <pre>
     *存放msgHead
     * </pre>
     */
    public com.google.protobuf.ByteString getMsghead() {
      return msghead_;
    }

    // optional bytes msgbody = 2;
    public static final int MSGBODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msgbody_;
    /**
     * <code>optional bytes msgbody = 2;</code>
     *
     * <pre>
     *存放某个message
     * </pre>
     */
    public boolean hasMsgbody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes msgbody = 2;</code>
     *
     * <pre>
     *存放某个message
     * </pre>
     */
    public com.google.protobuf.ByteString getMsgbody() {
      return msgbody_;
    }

    private void initFields() {
      msghead_ = com.google.protobuf.ByteString.EMPTY;
      msgbody_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsghead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, msgbody_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msgbody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.finger.pb.PBSocket.CMsgBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.CMsgBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.finger.pb.PBSocket.CMsgBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xapp.socket.CMsgBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.finger.pb.PBSocket.CMsgBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.finger.pb.PBSocket.CMsgBase.class, com.finger.pb.PBSocket.CMsgBase.Builder.class);
      }

      // Construct using com.finger.pb.PBSocket.CMsgBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msghead_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgbody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgBase_descriptor;
      }

      public com.finger.pb.PBSocket.CMsgBase getDefaultInstanceForType() {
        return com.finger.pb.PBSocket.CMsgBase.getDefaultInstance();
      }

      public com.finger.pb.PBSocket.CMsgBase build() {
        com.finger.pb.PBSocket.CMsgBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.finger.pb.PBSocket.CMsgBase buildPartial() {
        com.finger.pb.PBSocket.CMsgBase result = new com.finger.pb.PBSocket.CMsgBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msghead_ = msghead_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgbody_ = msgbody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.finger.pb.PBSocket.CMsgBase) {
          return mergeFrom((com.finger.pb.PBSocket.CMsgBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.finger.pb.PBSocket.CMsgBase other) {
        if (other == com.finger.pb.PBSocket.CMsgBase.getDefaultInstance()) return this;
        if (other.hasMsghead()) {
          setMsghead(other.getMsghead());
        }
        if (other.hasMsgbody()) {
          setMsgbody(other.getMsgbody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsghead()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.finger.pb.PBSocket.CMsgBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.finger.pb.PBSocket.CMsgBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes msghead = 1;
      private com.google.protobuf.ByteString msghead_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msghead = 1;</code>
       *
       * <pre>
       *存放msgHead
       * </pre>
       */
      public boolean hasMsghead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes msghead = 1;</code>
       *
       * <pre>
       *存放msgHead
       * </pre>
       */
      public com.google.protobuf.ByteString getMsghead() {
        return msghead_;
      }
      /**
       * <code>required bytes msghead = 1;</code>
       *
       * <pre>
       *存放msgHead
       * </pre>
       */
      public Builder setMsghead(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msghead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msghead = 1;</code>
       *
       * <pre>
       *存放msgHead
       * </pre>
       */
      public Builder clearMsghead() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msghead_ = getDefaultInstance().getMsghead();
        onChanged();
        return this;
      }

      // optional bytes msgbody = 2;
      private com.google.protobuf.ByteString msgbody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgbody = 2;</code>
       *
       * <pre>
       *存放某个message
       * </pre>
       */
      public boolean hasMsgbody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes msgbody = 2;</code>
       *
       * <pre>
       *存放某个message
       * </pre>
       */
      public com.google.protobuf.ByteString getMsgbody() {
        return msgbody_;
      }
      /**
       * <code>optional bytes msgbody = 2;</code>
       *
       * <pre>
       *存放某个message
       * </pre>
       */
      public Builder setMsgbody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msgbody = 2;</code>
       *
       * <pre>
       *存放某个message
       * </pre>
       */
      public Builder clearMsgbody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgbody_ = getDefaultInstance().getMsgbody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xapp.socket.CMsgBase)
    }

    static {
      defaultInstance = new CMsgBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xapp.socket.CMsgBase)
  }

  public interface CMsgHeadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 msgtype = 1;
    /**
     * <code>required int32 msgtype = 1;</code>
     *
     * <pre>
     *MessageType 类型
     * </pre>
     */
    boolean hasMsgtype();
    /**
     * <code>required int32 msgtype = 1;</code>
     *
     * <pre>
     *MessageType 类型
     * </pre>
     */
    int getMsgtype();

    // optional int32 msgcode = 2;
    /**
     * <code>optional int32 msgcode = 2;</code>
     *
     * <pre>
     *MessageCode 错误码
     * </pre>
     */
    boolean hasMsgcode();
    /**
     * <code>optional int32 msgcode = 2;</code>
     *
     * <pre>
     *MessageCode 错误码
     * </pre>
     */
    int getMsgcode();
  }
  /**
   * Protobuf type {@code xapp.socket.CMsgHead}
   */
  public static final class CMsgHead extends
      com.google.protobuf.GeneratedMessage
      implements CMsgHeadOrBuilder {
    // Use CMsgHead.newBuilder() to construct.
    private CMsgHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CMsgHead(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CMsgHead defaultInstance;
    public static CMsgHead getDefaultInstance() {
      return defaultInstance;
    }

    public CMsgHead getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CMsgHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgtype_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgcode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finger.pb.PBSocket.CMsgHead.class, com.finger.pb.PBSocket.CMsgHead.Builder.class);
    }

    public static com.google.protobuf.Parser<CMsgHead> PARSER =
        new com.google.protobuf.AbstractParser<CMsgHead>() {
      public CMsgHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CMsgHead(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CMsgHead> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 msgtype = 1;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgtype_;
    /**
     * <code>required int32 msgtype = 1;</code>
     *
     * <pre>
     *MessageType 类型
     * </pre>
     */
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgtype = 1;</code>
     *
     * <pre>
     *MessageType 类型
     * </pre>
     */
    public int getMsgtype() {
      return msgtype_;
    }

    // optional int32 msgcode = 2;
    public static final int MSGCODE_FIELD_NUMBER = 2;
    private int msgcode_;
    /**
     * <code>optional int32 msgcode = 2;</code>
     *
     * <pre>
     *MessageCode 错误码
     * </pre>
     */
    public boolean hasMsgcode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 msgcode = 2;</code>
     *
     * <pre>
     *MessageCode 错误码
     * </pre>
     */
    public int getMsgcode() {
      return msgcode_;
    }

    private void initFields() {
      msgtype_ = 0;
      msgcode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, msgcode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgcode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.finger.pb.PBSocket.CMsgHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.CMsgHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.finger.pb.PBSocket.CMsgHead prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xapp.socket.CMsgHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.finger.pb.PBSocket.CMsgHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.finger.pb.PBSocket.CMsgHead.class, com.finger.pb.PBSocket.CMsgHead.Builder.class);
      }

      // Construct using com.finger.pb.PBSocket.CMsgHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CMsgHead_descriptor;
      }

      public com.finger.pb.PBSocket.CMsgHead getDefaultInstanceForType() {
        return com.finger.pb.PBSocket.CMsgHead.getDefaultInstance();
      }

      public com.finger.pb.PBSocket.CMsgHead build() {
        com.finger.pb.PBSocket.CMsgHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.finger.pb.PBSocket.CMsgHead buildPartial() {
        com.finger.pb.PBSocket.CMsgHead result = new com.finger.pb.PBSocket.CMsgHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgtype_ = msgtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgcode_ = msgcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.finger.pb.PBSocket.CMsgHead) {
          return mergeFrom((com.finger.pb.PBSocket.CMsgHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.finger.pb.PBSocket.CMsgHead other) {
        if (other == com.finger.pb.PBSocket.CMsgHead.getDefaultInstance()) return this;
        if (other.hasMsgtype()) {
          setMsgtype(other.getMsgtype());
        }
        if (other.hasMsgcode()) {
          setMsgcode(other.getMsgcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgtype()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.finger.pb.PBSocket.CMsgHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.finger.pb.PBSocket.CMsgHead) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 msgtype = 1;
      private int msgtype_ ;
      /**
       * <code>required int32 msgtype = 1;</code>
       *
       * <pre>
       *MessageType 类型
       * </pre>
       */
      public boolean hasMsgtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgtype = 1;</code>
       *
       * <pre>
       *MessageType 类型
       * </pre>
       */
      public int getMsgtype() {
        return msgtype_;
      }
      /**
       * <code>required int32 msgtype = 1;</code>
       *
       * <pre>
       *MessageType 类型
       * </pre>
       */
      public Builder setMsgtype(int value) {
        bitField0_ |= 0x00000001;
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgtype = 1;</code>
       *
       * <pre>
       *MessageType 类型
       * </pre>
       */
      public Builder clearMsgtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtype_ = 0;
        onChanged();
        return this;
      }

      // optional int32 msgcode = 2;
      private int msgcode_ ;
      /**
       * <code>optional int32 msgcode = 2;</code>
       *
       * <pre>
       *MessageCode 错误码
       * </pre>
       */
      public boolean hasMsgcode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 msgcode = 2;</code>
       *
       * <pre>
       *MessageCode 错误码
       * </pre>
       */
      public int getMsgcode() {
        return msgcode_;
      }
      /**
       * <code>optional int32 msgcode = 2;</code>
       *
       * <pre>
       *MessageCode 错误码
       * </pre>
       */
      public Builder setMsgcode(int value) {
        bitField0_ |= 0x00000002;
        msgcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgcode = 2;</code>
       *
       * <pre>
       *MessageCode 错误码
       * </pre>
       */
      public Builder clearMsgcode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgcode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xapp.socket.CMsgHead)
    }

    static {
      defaultInstance = new CMsgHead(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xapp.socket.CMsgHead)
  }

  public interface CS_LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userName = 1;
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string password = 2;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    // required string serverID = 3;
    /**
     * <code>required string serverID = 3;</code>
     *
     * <pre>
     *服务器id分服
     * </pre>
     */
    boolean hasServerID();
    /**
     * <code>required string serverID = 3;</code>
     *
     * <pre>
     *服务器id分服
     * </pre>
     */
    java.lang.String getServerID();
    /**
     * <code>required string serverID = 3;</code>
     *
     * <pre>
     *服务器id分服
     * </pre>
     */
    com.google.protobuf.ByteString
        getServerIDBytes();
  }
  /**
   * Protobuf type {@code xapp.socket.CS_Login}
   */
  public static final class CS_Login extends
      com.google.protobuf.GeneratedMessage
      implements CS_LoginOrBuilder {
    // Use CS_Login.newBuilder() to construct.
    private CS_Login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CS_Login(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CS_Login defaultInstance;
    public static CS_Login getDefaultInstance() {
      return defaultInstance;
    }

    public CS_Login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CS_Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serverID_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_CS_Login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_CS_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finger.pb.PBSocket.CS_Login.class, com.finger.pb.PBSocket.CS_Login.Builder.class);
    }

    public static com.google.protobuf.Parser<CS_Login> PARSER =
        new com.google.protobuf.AbstractParser<CS_Login>() {
      public CS_Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CS_Login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CS_Login> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userName = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string serverID = 3;
    public static final int SERVERID_FIELD_NUMBER = 3;
    private java.lang.Object serverID_;
    /**
     * <code>required string serverID = 3;</code>
     *
     * <pre>
     *服务器id分服
     * </pre>
     */
    public boolean hasServerID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string serverID = 3;</code>
     *
     * <pre>
     *服务器id分服
     * </pre>
     */
    public java.lang.String getServerID() {
      java.lang.Object ref = serverID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverID = 3;</code>
     *
     * <pre>
     *服务器id分服
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServerIDBytes() {
      java.lang.Object ref = serverID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userName_ = "";
      password_ = "";
      serverID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServerIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServerIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.finger.pb.PBSocket.CS_Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CS_Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.finger.pb.PBSocket.CS_Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.CS_Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.finger.pb.PBSocket.CS_Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xapp.socket.CS_Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.finger.pb.PBSocket.CS_LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CS_Login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CS_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.finger.pb.PBSocket.CS_Login.class, com.finger.pb.PBSocket.CS_Login.Builder.class);
      }

      // Construct using com.finger.pb.PBSocket.CS_Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        serverID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_CS_Login_descriptor;
      }

      public com.finger.pb.PBSocket.CS_Login getDefaultInstanceForType() {
        return com.finger.pb.PBSocket.CS_Login.getDefaultInstance();
      }

      public com.finger.pb.PBSocket.CS_Login build() {
        com.finger.pb.PBSocket.CS_Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.finger.pb.PBSocket.CS_Login buildPartial() {
        com.finger.pb.PBSocket.CS_Login result = new com.finger.pb.PBSocket.CS_Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverID_ = serverID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.finger.pb.PBSocket.CS_Login) {
          return mergeFrom((com.finger.pb.PBSocket.CS_Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.finger.pb.PBSocket.CS_Login other) {
        if (other == com.finger.pb.PBSocket.CS_Login.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasServerID()) {
          bitField0_ |= 0x00000004;
          serverID_ = other.serverID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (!hasServerID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.finger.pb.PBSocket.CS_Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.finger.pb.PBSocket.CS_Login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userName = 1;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // required string serverID = 3;
      private java.lang.Object serverID_ = "";
      /**
       * <code>required string serverID = 3;</code>
       *
       * <pre>
       *服务器id分服
       * </pre>
       */
      public boolean hasServerID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string serverID = 3;</code>
       *
       * <pre>
       *服务器id分服
       * </pre>
       */
      public java.lang.String getServerID() {
        java.lang.Object ref = serverID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverID = 3;</code>
       *
       * <pre>
       *服务器id分服
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServerIDBytes() {
        java.lang.Object ref = serverID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverID = 3;</code>
       *
       * <pre>
       *服务器id分服
       * </pre>
       */
      public Builder setServerID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverID = 3;</code>
       *
       * <pre>
       *服务器id分服
       * </pre>
       */
      public Builder clearServerID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverID_ = getDefaultInstance().getServerID();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverID = 3;</code>
       *
       * <pre>
       *服务器id分服
       * </pre>
       */
      public Builder setServerIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xapp.socket.CS_Login)
    }

    static {
      defaultInstance = new CS_Login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xapp.socket.CS_Login)
  }

  public interface SC_LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userName = 1;
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // required string password = 2;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code xapp.socket.SC_Login}
   */
  public static final class SC_Login extends
      com.google.protobuf.GeneratedMessage
      implements SC_LoginOrBuilder {
    // Use SC_Login.newBuilder() to construct.
    private SC_Login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SC_Login(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SC_Login defaultInstance;
    public static SC_Login getDefaultInstance() {
      return defaultInstance;
    }

    public SC_Login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SC_Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_SC_Login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.finger.pb.PBSocket.internal_static_xapp_socket_SC_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.finger.pb.PBSocket.SC_Login.class, com.finger.pb.PBSocket.SC_Login.Builder.class);
    }

    public static com.google.protobuf.Parser<SC_Login> PARSER =
        new com.google.protobuf.AbstractParser<SC_Login>() {
      public SC_Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SC_Login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SC_Login> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userName = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 1;</code>
     *
     * <pre>
     *用户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     *
     * <pre>
     *密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userName_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.finger.pb.PBSocket.SC_Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.SC_Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.finger.pb.PBSocket.SC_Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.finger.pb.PBSocket.SC_Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.finger.pb.PBSocket.SC_Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xapp.socket.SC_Login}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.finger.pb.PBSocket.SC_LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_SC_Login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_SC_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.finger.pb.PBSocket.SC_Login.class, com.finger.pb.PBSocket.SC_Login.Builder.class);
      }

      // Construct using com.finger.pb.PBSocket.SC_Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.finger.pb.PBSocket.internal_static_xapp_socket_SC_Login_descriptor;
      }

      public com.finger.pb.PBSocket.SC_Login getDefaultInstanceForType() {
        return com.finger.pb.PBSocket.SC_Login.getDefaultInstance();
      }

      public com.finger.pb.PBSocket.SC_Login build() {
        com.finger.pb.PBSocket.SC_Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.finger.pb.PBSocket.SC_Login buildPartial() {
        com.finger.pb.PBSocket.SC_Login result = new com.finger.pb.PBSocket.SC_Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.finger.pb.PBSocket.SC_Login) {
          return mergeFrom((com.finger.pb.PBSocket.SC_Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.finger.pb.PBSocket.SC_Login other) {
        if (other == com.finger.pb.PBSocket.SC_Login.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.finger.pb.PBSocket.SC_Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.finger.pb.PBSocket.SC_Login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userName = 1;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 1;</code>
       *
       * <pre>
       *用户id
       * </pre>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      // required string password = 2;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       *
       * <pre>
       *密码
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xapp.socket.SC_Login)
    }

    static {
      defaultInstance = new SC_Login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xapp.socket.SC_Login)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xapp_socket_CMsgBase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xapp_socket_CMsgBase_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xapp_socket_CMsgHead_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xapp_socket_CMsgHead_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xapp_socket_CS_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xapp_socket_CS_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xapp_socket_SC_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xapp_socket_SC_Login_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014socket.proto\022\013xapp.socket\032\014battle.prot" +
      "o\",\n\010CMsgBase\022\017\n\007msghead\030\001 \002(\014\022\017\n\007msgbod" +
      "y\030\002 \001(\014\",\n\010CMsgHead\022\017\n\007msgtype\030\001 \002(\005\022\017\n\007" +
      "msgcode\030\002 \001(\005\"@\n\010CS_Login\022\020\n\010userName\030\001 " +
      "\002(\t\022\020\n\010password\030\002 \002(\t\022\020\n\010serverID\030\003 \002(\t\"" +
      ".\n\010SC_Login\022\020\n\010userName\030\001 \002(\t\022\020\n\010passwor" +
      "d\030\002 \002(\t*6\n\013MessageCode\022\016\n\nSYS_NORMAL\020\001\022\027" +
      "\n\023SYS_NOT_ENOUGH_GOLD\020\002*#\n\013MessageType\022\024" +
      "\n\016MSG_HEART_BEAT\020\241\215\006B\031\n\rcom.finger.pbB\010P" +
      "BSocket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_xapp_socket_CMsgBase_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_xapp_socket_CMsgBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xapp_socket_CMsgBase_descriptor,
              new java.lang.String[] { "Msghead", "Msgbody", });
          internal_static_xapp_socket_CMsgHead_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_xapp_socket_CMsgHead_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xapp_socket_CMsgHead_descriptor,
              new java.lang.String[] { "Msgtype", "Msgcode", });
          internal_static_xapp_socket_CS_Login_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_xapp_socket_CS_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xapp_socket_CS_Login_descriptor,
              new java.lang.String[] { "UserName", "Password", "ServerID", });
          internal_static_xapp_socket_SC_Login_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_xapp_socket_SC_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xapp_socket_SC_Login_descriptor,
              new java.lang.String[] { "UserName", "Password", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xapp.battle.Battle.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
